#!/usr/bin/env bash

script_dir=$(dirname "$0")

arch=x64
build=false
build_args=
config=Release
coreclr_root=~/Code/git/coreclr
# TODO: Add support for excluding certain files.
to=.
just_corelib=false

while getopts ':C:a:b:cdt:' opt; do
    case "$opt" in
        C) coreclr_root=$OPTARG ;;
        a) arch=$OPTARG ;;
        b) build=true; build_args=$OPTARG ;;
        c) just_corelib=true ;;
        d) config=Debug ;;
        t) to=$OPTARG ;;
        '?') echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
    esac
done

coreclr_bins=$coreclr_root/bin/Product/Windows_NT.$arch.$config

if "$build"; then
    pushd "$coreclr_root"
    "$script_dir/build_mscorlib" $build_args # $build_args is intentionally unquoted so more than 1 arg can be passed
    popd
fi

# Copy all of the files in the bin directory
if "$just_corelib"; then
    cp "$coreclr_bins/System.Private.CoreLib.ni.dll" "$to"
else
    cp "$coreclr_bins"/* "$to" 2>/dev/null
fi

# Copy the PDBs as well
cp "$coreclr_bins/PDB"/* "$to"
