#!/usr/bin/env bash

# TODO: Not portable to Bourne shell.
script_dir=$(dirname "${BASH_SOURCE[0]}")

app_args=
copy=false
loud=false
publish=false

while getopts ':a:clp' opt; do
    case "$opt" in
        a) app_args=$OPTARG ;;
        c) copy=true ;; # TODO: Add support for passing args.
        l) loud=true ;;
        p) publish=true ;; # TODO: Add support for passing args.
        \?) echo "Unknown option: -$OPTARG" >&2; exit 1 ;;
    esac

    # TODO: handle "$opt" == ":"
    # TODO: handle -- so you can write run_app -- [app args]
done

output_file=/dev/null
if "$loud"; then
    output_file=/dev/stdout
fi

# Publish before copying.
if "$publish"; then
    "$script_dir/publish_app" >"$output_file"
fi

if "$copy"; then
    "$script_dir/copy_coreclr" -t publish >"$output_file"
fi

# Run the app, which will have the same name as the dir we're in
name=$(basename "$PWD")
exec "$PWD/publish/$name" $app_args # we do not want to redirect this
