#!/usr/bin/env bash

# TODO: Not portable to Bourne shell.
script_dir=$(dirname "${BASH_SOURCE[0]}")

app_args=
clr_args=()
fx_args=()
loud=false
publish=false
silent=false

while getopts ':a:c:f:lps' opt; do
    case "$opt" in
        a) app_args=$OPTARG ;; # TODO: Better support for passing args.
        c) clr_args+=("$OPTARG") ;;
        f) fx_args+=("$OPTARG") ;;
        l) loud=true ;;
        p) publish=true ;; # TODO: Add support for passing args.
        s) silent=true ;;
        \?) echo "Unknown option: -$OPTARG" >&2; exit 1 ;;
    esac

    # TODO: handle "$opt" == ":"
    # TODO: handle -- so you can write run_app -- [app args]
done

output_file=/dev/null
if "$loud"; then
    output_file=/dev/stdout
fi

error_file=/dev/stderr
if "$silent"; then
    error_file=/dev/null
fi

# Publish before copying.
if "$publish"; then
    "$script_dir/publish_app" >"$output_file" 2>"$error_file"
fi

if [ "${#clr_args[@]}" -ne 0 ]; then
    "$script_dir/copy_coreclr" -t publish "${clr_args[@]}" >"$output_file" 2>"$error_file"
fi

if [ "${#fx_args[@]}" -ne 0 ]; then
    "$script_dir/copy_corefx" -t publish "${fx_args[@]}" >"$output_file" 2>"$error_file"
fi

# Run the app, which will have the same name as the dir we're in
name=$(basename "$PWD")
exec "$PWD/publish/$name" $app_args # we do not want to redirect this
